### ISSUE TITLE
Email doesn't go to domain ids

### ISSUE THREAD

**Issue by huzanf** [rabdill/email-contact-form#1]
Hi.
I tried using your script. The emails go to gmail ids' but they don't go to business email ids.

Could you please help me rectify the same.

Best,
H

**Comment by rabdill** [comment]
Hi! I'm glad the script was working for Gmail -- unfortunately, that probably means the emails being sent by the form are being sent properly and then getting caught in your business's spam filter. The emails will be coming from whatever IP your server is at, which likely looks suspicious to the mail server. Have you checked for anything there?

**Comment by huzanf** [comment]
Hi,
They're not even going to the SPAM/Junk box. There is no email received.
